funcionalidad del modulo alumnos
jpmvalencia/Clase8 pull request #1
Opened 2023-04-24 20:30 UTC by Ricardozapata20

permite ingresal en nombre y 3 notas de un alumno 
verifica si se quiere ingresar otro alumno
calcula el promedio de cada alumno ingresado
muestra en forma tabular los promedios de cada uno

2023-04-24 20:36 UTC, jpmvalencia requested changes
Por favor hacer la funcionalidad para que muestre los alumnos que perdieron en forma tabular.

2023-04-24 20:36 UTC, jpmvalencia commented on alumnos.py
> +            print(alumno[0]+"\t" +str(round(promedio, 1)))
Hacer la funcionalidad para que muestre en forma tabular los alumnos que perdieron

2023-04-25 02:12 UTC, Ricardozapata20 commented
se agrega la funcionalidad que muestra la lista de estudiantes que perdieron la materia

2023-04-25 02:14 UTC, Ricardozapata20 commented on alumnos.py
> +            print(alumno[0]+"\t" +str(round(promedio, 1)))
listo quedo al pendiente

2023-04-25 02:17 UTC, merged

2023-04-25 02:28 UTC, jpmvalencia commented
Listo, todo completo

2023-04-25 02:31 UTC, jpmvalencia commented
Se hace el merge de alumnos con develop